name: KillerMoney
main: net.diecode.KillerMoney.BukkitMain
version: 4.0.0
softdepend: [Vault, MobArena, MineChart]
author: diecode
website: http://dev.bukkit.org/bukkit-plugins/killermoney/
commands:
    km:
        description: "This is the main command of KillerMoney"
        usage: "Please type /<command> help"
        aliases: [killermoney]
        default: true