name: KillerMoney
main: net.diecode.KillerMoney.KillerMoney
version: 3.21
softdepend: [Vault, MobArena, MineStatus-Universal]
author: diecode
website: http://dev.bukkit.org/bukkit-plugins/killermoney/

commands:
    killermoney:
        description: "This is the main command of KillerMoney"
        usage: "Please type /<command> help"
        aliases: [km]
        default: true

permissions:
    killermoney.admin:
        description: Reload KillerMoney's configurations and locale files
        default: op