name: KillerMoney
main: net.diecode.killermoney.BukkitMain
version: 4.3.2
softdepend: [Vault, MobArena, Multiverse-Core]
author: diecode
website: http://dev.bukkit.org/bukkit-plugins/killermoney/
commands:
    km:
        description: "This is the main command of KillerMoney"
        usage: "Please type /<command> help"
        aliases: [killermoney]
        default: true
    kmadmin:
        description: "This is the admin command of KillerMoney"
        usage: "Please usable /<command> help"
        aliases: [killermoneyadmin, kma]
        default: true